In [96]:
import pandas as pd
import os
import numpy as np
import re
from collections import Counter
import matplotlib.pyplot as plt 
import seaborn as sb
from bs4 import BeautifulSoup
from urllib.request import urlopen
import requests

## TRANSFORMATION ##

    ''' Unifying all the dataframes and data acquired.'''

In [97]:
df_1 = pd.read_csv("../data/Dataset Global Fashion Brands Brand Equity Ranking Growth Rate  COO ROO 2001-2021.csv")
df_1

,BrandName,BrandOriginCountry,BrandOriginRegion,BrandSector,BrandSubSector,Rank2001,Rank2002,Rank2003,Rank2004,Rank2005,...,GrowthRate2012,GrowthRate2013,GrowthRate2014,GrowthRate2015,GrowthRate2016,GrowthRate2017,GrowthRate2018,GrowthRate2019,GrowthRate2020,GrowthRate2021
0,Louis Vuitton,France,Europe,Fashion,Luxury,38.0,41.0,45.0,44.0,18.0,...,1.75,5.58,-9.40,-1.34,7.86,-4.50,22.83,14.46,-1.56,15.91
1,Chanel,France,Europe,Fashion,Luxury,61.0,64.0,61.0,64.0,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.64,-4.21,4.27
2,Hermès,France,Europe,Fashion,Luxury,NaN,NaN,73.0,79.0,82.0,...,15.23,23.20,17.87,21.91,17.26,10.73,15.21,9.46,0.23,20.26
3,L’Oréal,France,Europe,Fashion,Cosmetics,NaN,54.0,47.0,49.0,52.0,...,1.40,11.94,2.92,6.26,1.22,-2.34,4.01,4.39,8.32,-0.41
4,Dior,France,Europe,Fashion,Luxury,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-6.56,13.87,15.74,-0.94,17.30
5,Sephora,France,Europe,Fashion,Cosmetics,100.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Lancome,France,Europe,Fashion,Cosmetics,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Adidas,Germany,Europe,Fashion,Sportswear,70.0,68.0,67.0,69.0,71.0,...,8.86,12.48,-2.08,-7.69,15.77,16.88,16.88,11.33,0.65,10.86
8,Boss,Germany,Europe,Fashion,Apparel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.07,-100.00,NaN,NaN,NaN,NaN,NaN
9,Nivea,Germany,Europe,Fashion,Cosmetics,87.0,91.0,92.0,97.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Puma,Germany,Europe,Fashion,Sportswear,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Gucci,Italy,Europe,Fashion,Luxury,50.0,52.0,53.0,59.0,49.0,...,7.79,7.46,2.31,-14.47,5.66,6.22,29.82,23.23,-1.72,6.26
12,Prada,Italy,Europe,Fashion,Luxury,NaN,86.0,87.0,95.0,93.0,...,NaN,30.41,7.31,4.10,-11.54,-14.32,2.04,-0.64,-5.98,20.49
13,Benetton,Italy,Europe,Fashion,Apparel,100.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Bulgari,Italy,Europe,Fashion,Luxury,NaN,NaN,NaN,NaN,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Armani,Italy,Europe,Fashion,Luxury,91.0,100.0,NaN,93.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Zara,Spain,Europe,Fashion,Apparel,NaN,NaN,NaN,NaN,77.0,...,17.64,14.05,12.06,15.71,19.49,10.78,-4.64,-3.03,-13.47,-9.14
17,H&M,Sweden,Europe,Fashion,Apparel,NaN,NaN,NaN,NaN,NaN,...,0.68,9.64,16.04,5.40,2.07,-9.67,-17.87,-2.86,-14.30,0.89
18,Cartier,Switzerland,Europe,Fashion,Luxury,NaN,NaN,NaN,91.0,89.0,...,14.93,25.51,8.00,6.38,-2.35,-2.47,1.31,7.14,-8.52,8.90
19,Swatch,Switzerland,Europe,Fashion,Luxury,99.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Rolex,Switzerland,Europe,Fashion,Luxury,69.0,69.0,68.0,70.0,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Burberry,U.K.,Europe,Fashion,Luxury,NaN,NaN,NaN,NaN,NaN,...,16.35,19.51,7.80,4.99,-8.70,-4.23,-2.84,4.33,-7.61,8.03
22,Nike,U.S.A.,America,Fashion,Sportswear,34.0,35.0,33.0,31.0,30.0,...,4.12,12.95,16.33,16.08,8.51,7.94,11.47,7.49,6.21,23.70
23,Tiffany,U.S.A.,America,Fashion,Luxury,73.0,72.0,70.0,75.0,81.0,...,14.70,5.45,9.12,6.23,-8.64,-6.37,4.60,-5.44,-6.92,10.43
24,Levi's,U.S.A.,America,Fashion,Apparel,67.0,73.0,77.0,85.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Gap,U.S.A.,America,Fashion,Apparel,31.0,36.0,36.0,38.0,40.0,...,-7.65,5.07,5.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Ralph & Lauren,U.S.A.,America,Fashion,Apparel,NaN,NaN,NaN,NaN,NaN,...,NaN,13.52,8.62,-7.03,-11.60,-100.00,NaN,NaN,NaN,NaN
27,Estee,U.S.A.,America,Fashion,Cosmetics,NaN,NaN,NaN,92.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Avon,U.S.A.,America,Fashion,Cosmetics,60.0,62.0,57.0,58.0,59.0,...,-4.19,-10.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Polo,U.S.A.,America,Fashion,Luxury,85.0,95.0,95.0,100.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
df_2 = pd.read_csv("../data/LuxFashion-Q42019.csv")
df_2

,Brand,Social Visibility,Web Visibility,Sentiment,Growth,Search,Total
0,Hermes,18.40,67.57,100.00,100.00,87.88,373.85
1,Gucci,100.00,100.00,53.61,23.56,85.14,362.31
2,Louis Vuitton,35.17,50.61,51.18,13.68,100.00,250.64
3,Chanel,71.26,90.20,48.21,2.68,30.78,243.13
4,Coach,9.29,56.64,64.26,0.00,41.18,171.37
5,Prada,21.52,34.19,38.19,56.09,16.69,166.68
6,Fendi,10.74,14.63,58.47,65.87,16.09,165.80
7,Dior,45.01,56.86,37.65,1.58,18.14,159.24
8,Calvin Klein,13.75,22.25,62.08,8.06,50.99,157.13
9,Ted Baker,1.87,6.51,47.14,48.81,34.81,139.14
10,Versace,21.68,28.79,39.09,13.95,30.17,133.68
11,Michael Kors,5.91,17.59,58.40,0.00,49.79,131.69
12,Cartier,10.44,34.93,41.27,19.37,16.83,122.84
13,Burberry,9.44,27.35,50.82,0.00,32.75,120.36
14,Ralph Lauren,8.39,26.28,37.34,0.00,47.83,119.84
15,Tory Burch,2.12,5.56,79.04,0.00,25.57,112.29
16,Armani,7.30,27.52,53.71,6.49,11.69,106.71
17,Yves Saint Laurent,21.74,33.01,36.31,0.00,11.54,102.60
18,Breitling,0.48,17.09,39.04,31.91,8.96,97.48
19,Jovani,0.33,0.87,72.29,10.29,1.77,85.55
20,Givenchy,6.57,17.44,41.05,7.61,11.87,84.54
21,Kenzo,2.96,8.80,65.49,0.00,6.72,83.97
22,Chloe,2.45,11.01,58.93,0.00,9.85,82.24
23,DKNY,1.38,4.49,67.95,0.00,6.38,80.20
24,Christian Louboutin,4.58,12.43,50.67,0.00,11.71,79.39
25,Salvatore Ferragamo,1.62,8.06,54.06,9.64,5.13,78.51
26,Dolce & Gabbana,6.97,7.76,40.87,0.69,1.99,58.28
27,Dsquared2,1.04,2.41,51.40,0.00,3.13,57.98
28,Paul Smith,1.34,11.18,22.62,1.09,11.19,47.42
29,Lanvin,1.23,2.40,19.21,0.00,1.26,24.10

In [99]:
df_3 = pd.read_csv("../data/100_fashion_money.csv")
df_3.sample(5)

     Unnamed: 0   Rank       Company    Mcap $     Type
186         186  186.0        ESCADA    $101 m  Private
164         164  164.0          ASOS    $600 m   Public
3             3    3.0        Hermès  $130.4 b   Public
73           73   73.0  Under Armour   $3.01 b   Public
49           49   49.0      Skechers   $5.22 b   Public

    ''' To be able to merge the dataframes first, I'll need to change the different column names refering to the brand name and make it the same.'''

In [100]:
df_1.rename(columns = {'BrandName':'Brand'}, inplace = True)
df_1.sample(3)

,Brand,BrandOriginCountry,BrandOriginRegion,BrandSector,BrandSubSector,Rank2001,Rank2002,Rank2003,Rank2004,Rank2005,...,GrowthRate2012,GrowthRate2013,GrowthRate2014,GrowthRate2015,GrowthRate2016,GrowthRate2017,GrowthRate2018,GrowthRate2019,GrowthRate2020,GrowthRate2021
18,Cartier,Switzerland,Europe,Fashion,Luxury,NaN,NaN,NaN,91.0,89.0,...,14.93,25.51,8.00,6.38,-2.35,-2.47,1.31,7.14,-8.52,8.90
28,Avon,U.S.A.,America,Fashion,Cosmetics,60.0,62.0,57.0,58.0,59.0,...,-4.19,-10.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,H&M,Sweden,Europe,Fashion,Apparel,NaN,NaN,NaN,NaN,NaN,...,0.68,9.64,16.04,5.40,2.07,-9.67,-17.87,-2.86,-14.30,0.89

    ''' Also changing the brand name "Hermes" as is it written in ifferent ways and won't be able to merge. '''

In [101]:
df_1.at[2, "Brand"] = "Hermes"
df_1

,Brand,BrandOriginCountry,BrandOriginRegion,BrandSector,BrandSubSector,Rank2001,Rank2002,Rank2003,Rank2004,Rank2005,...,GrowthRate2012,GrowthRate2013,GrowthRate2014,GrowthRate2015,GrowthRate2016,GrowthRate2017,GrowthRate2018,GrowthRate2019,GrowthRate2020,GrowthRate2021
0,Louis Vuitton,France,Europe,Fashion,Luxury,38.0,41.0,45.0,44.0,18.0,...,1.75,5.58,-9.40,-1.34,7.86,-4.50,22.83,14.46,-1.56,15.91
1,Chanel,France,Europe,Fashion,Luxury,61.0,64.0,61.0,64.0,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.64,-4.21,4.27
2,Hermes,France,Europe,Fashion,Luxury,NaN,NaN,73.0,79.0,82.0,...,15.23,23.20,17.87,21.91,17.26,10.73,15.21,9.46,0.23,20.26
3,L’Oréal,France,Europe,Fashion,Cosmetics,NaN,54.0,47.0,49.0,52.0,...,1.40,11.94,2.92,6.26,1.22,-2.34,4.01,4.39,8.32,-0.41
4,Dior,France,Europe,Fashion,Luxury,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-6.56,13.87,15.74,-0.94,17.30
5,Sephora,France,Europe,Fashion,Cosmetics,100.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Lancome,France,Europe,Fashion,Cosmetics,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Adidas,Germany,Europe,Fashion,Sportswear,70.0,68.0,67.0,69.0,71.0,...,8.86,12.48,-2.08,-7.69,15.77,16.88,16.88,11.33,0.65,10.86
8,Boss,Germany,Europe,Fashion,Apparel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.07,-100.00,NaN,NaN,NaN,NaN,NaN
9,Nivea,Germany,Europe,Fashion,Cosmetics,87.0,91.0,92.0,97.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Puma,Germany,Europe,Fashion,Sportswear,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Gucci,Italy,Europe,Fashion,Luxury,50.0,52.0,53.0,59.0,49.0,...,7.79,7.46,2.31,-14.47,5.66,6.22,29.82,23.23,-1.72,6.26
12,Prada,Italy,Europe,Fashion,Luxury,NaN,86.0,87.0,95.0,93.0,...,NaN,30.41,7.31,4.10,-11.54,-14.32,2.04,-0.64,-5.98,20.49
13,Benetton,Italy,Europe,Fashion,Apparel,100.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Bulgari,Italy,Europe,Fashion,Luxury,NaN,NaN,NaN,NaN,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Armani,Italy,Europe,Fashion,Luxury,91.0,100.0,NaN,93.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Zara,Spain,Europe,Fashion,Apparel,NaN,NaN,NaN,NaN,77.0,...,17.64,14.05,12.06,15.71,19.49,10.78,-4.64,-3.03,-13.47,-9.14
17,H&M,Sweden,Europe,Fashion,Apparel,NaN,NaN,NaN,NaN,NaN,...,0.68,9.64,16.04,5.40,2.07,-9.67,-17.87,-2.86,-14.30,0.89
18,Cartier,Switzerland,Europe,Fashion,Luxury,NaN,NaN,NaN,91.0,89.0,...,14.93,25.51,8.00,6.38,-2.35,-2.47,1.31,7.14,-8.52,8.90
19,Swatch,Switzerland,Europe,Fashion,Luxury,99.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Rolex,Switzerland,Europe,Fashion,Luxury,69.0,69.0,68.0,70.0,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Burberry,U.K.,Europe,Fashion,Luxury,NaN,NaN,NaN,NaN,NaN,...,16.35,19.51,7.80,4.99,-8.70,-4.23,-2.84,4.33,-7.61,8.03
22,Nike,U.S.A.,America,Fashion,Sportswear,34.0,35.0,33.0,31.0,30.0,...,4.12,12.95,16.33,16.08,8.51,7.94,11.47,7.49,6.21,23.70
23,Tiffany,U.S.A.,America,Fashion,Luxury,73.0,72.0,70.0,75.0,81.0,...,14.70,5.45,9.12,6.23,-8.64,-6.37,4.60,-5.44,-6.92,10.43
24,Levi's,U.S.A.,America,Fashion,Apparel,67.0,73.0,77.0,85.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Gap,U.S.A.,America,Fashion,Apparel,31.0,36.0,36.0,38.0,40.0,...,-7.65,5.07,5.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Ralph & Lauren,U.S.A.,America,Fashion,Apparel,NaN,NaN,NaN,NaN,NaN,...,NaN,13.52,8.62,-7.03,-11.60,-100.00,NaN,NaN,NaN,NaN
27,Estee,U.S.A.,America,Fashion,Cosmetics,NaN,NaN,NaN,92.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Avon,U.S.A.,America,Fashion,Cosmetics,60.0,62.0,57.0,58.0,59.0,...,-4.19,-10.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Polo,U.S.A.,America,Fashion,Luxury,85.0,95.0,95.0,100.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
df_3.rename(columns={"Company": "Brand"}, inplace=True)
df_3

     Unnamed: 0   Rank           Brand    Mcap $     Type
0             0    NaN             NaN       NaN      NaN
1             1    1.0            LVMH  $308.9 b   Public
2             2    2.0            Nike  $133.8 b   Public
3             3    3.0          Hermès  $130.4 b   Public
4             4    4.0  Christian Dior  $108.7 b   Public
..          ...    ...             ...       ...      ...
183         183  183.0      Supergroup    $107 m   Public
184         184  184.0           Rue21    $106 m  Private
185         185  185.0            Aldo    $102 m  Private
186         186  186.0          ESCADA    $101 m  Private
187         187  187.0         Express     $80 m   Public

[188 rows x 5 columns]

In [103]:
df_3.at[3, "Brand"] = "Hermes"
df_3

     Unnamed: 0   Rank           Brand    Mcap $     Type
0             0    NaN             NaN       NaN      NaN
1             1    1.0            LVMH  $308.9 b   Public
2             2    2.0            Nike  $133.8 b   Public
3             3    3.0          Hermes  $130.4 b   Public
4             4    4.0  Christian Dior  $108.7 b   Public
..          ...    ...             ...       ...      ...
183         183  183.0      Supergroup    $107 m   Public
184         184  184.0           Rue21    $106 m  Private
185         185  185.0            Aldo    $102 m  Private
186         186  186.0          ESCADA    $101 m  Private
187         187  187.0         Express     $80 m   Public

[188 rows x 5 columns]

In [104]:
merged_1 = pd.merge(df_1, df_2, on="Brand", how="right")
merged_1

,Brand,BrandOriginCountry,BrandOriginRegion,BrandSector,BrandSubSector,Rank2001,Rank2002,Rank2003,Rank2004,Rank2005,...,GrowthRate2018,GrowthRate2019,GrowthRate2020,GrowthRate2021,Social Visibility,Web Visibility,Sentiment,Growth,Search,Total
0,Hermes,France,Europe,Fashion,Luxury,NaN,NaN,73.0,79.0,82.0,...,15.21,9.46,0.23,20.26,18.40,67.57,100.00,100.00,87.88,373.85
1,Gucci,Italy,Europe,Fashion,Luxury,50.0,52.0,53.0,59.0,49.0,...,29.82,23.23,-1.72,6.26,100.00,100.00,53.61,23.56,85.14,362.31
2,Louis Vuitton,France,Europe,Fashion,Luxury,38.0,41.0,45.0,44.0,18.0,...,22.83,14.46,-1.56,15.91,35.17,50.61,51.18,13.68,100.00,250.64
3,Chanel,France,Europe,Fashion,Luxury,61.0,64.0,61.0,64.0,65.0,...,NaN,10.64,-4.21,4.27,71.26,90.20,48.21,2.68,30.78,243.13
4,Coach,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9.29,56.64,64.26,0.00,41.18,171.37
5,Prada,Italy,Europe,Fashion,Luxury,NaN,86.0,87.0,95.0,93.0,...,2.04,-0.64,-5.98,20.49,21.52,34.19,38.19,56.09,16.69,166.68
6,Fendi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,10.74,14.63,58.47,65.87,16.09,165.80
7,Dior,France,Europe,Fashion,Luxury,NaN,NaN,NaN,NaN,NaN,...,13.87,15.74,-0.94,17.30,45.01,56.86,37.65,1.58,18.14,159.24
8,Calvin Klein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.75,22.25,62.08,8.06,50.99,157.13
9,Ted Baker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.87,6.51,47.14,48.81,34.81,139.14
10,Versace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,21.68,28.79,39.09,13.95,30.17,133.68
11,Michael Kors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.91,17.59,58.40,0.00,49.79,131.69
12,Cartier,Switzerland,Europe,Fashion,Luxury,NaN,NaN,NaN,91.0,89.0,...,1.31,7.14,-8.52,8.90,10.44,34.93,41.27,19.37,16.83,122.84
13,Burberry,U.K.,Europe,Fashion,Luxury,NaN,NaN,NaN,NaN,NaN,...,-2.84,4.33,-7.61,8.03,9.44,27.35,50.82,0.00,32.75,120.36
14,Ralph Lauren,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.39,26.28,37.34,0.00,47.83,119.84
15,Tory Burch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.12,5.56,79.04,0.00,25.57,112.29
16,Armani,Italy,Europe,Fashion,Luxury,91.0,100.0,NaN,93.0,95.0,...,NaN,NaN,NaN,NaN,7.30,27.52,53.71,6.49,11.69,106.71
17,Yves Saint Laurent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,21.74,33.01,36.31,0.00,11.54,102.60
18,Breitling,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.48,17.09,39.04,31.91,8.96,97.48
19,Jovani,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.33,0.87,72.29,10.29,1.77,85.55
20,Givenchy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6.57,17.44,41.05,7.61,11.87,84.54
21,Kenzo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.96,8.80,65.49,0.00,6.72,83.97
22,Chloe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.45,11.01,58.93,0.00,9.85,82.24
23,DKNY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.38,4.49,67.95,0.00,6.38,80.20
24,Christian Louboutin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.58,12.43,50.67,0.00,11.71,79.39
25,Salvatore Ferragamo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.62,8.06,54.06,9.64,5.13,78.51
26,Dolce & Gabbana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6.97,7.76,40.87,0.69,1.99,58.28
27,Dsquared2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.04,2.41,51.40,0.00,3.13,57.98
28,Paul Smith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.34,11.18,22.62,1.09,11.19,47.42
29,Lanvin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.23,2.40,19.21,0.00,1.26,24.10

In [106]:
merged_df = pd.merge(merged_1,df_3, on="Brand", how="left")
merged_df.sample(10)

,Brand,BrandOriginCountry,BrandOriginRegion,BrandSector,BrandSubSector,Rank2001,Rank2002,Rank2003,Rank2004,Rank2005,...,Social Visibility,Web Visibility,Sentiment,Growth,Search,Total,Unnamed: 0,Rank,Mcap $,Type
23,DKNY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.38,4.49,67.95,0.00,6.38,80.20,NaN,NaN,NaN,NaN
29,Lanvin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.23,2.40,19.21,0.00,1.26,24.10,NaN,NaN,NaN,NaN
16,Armani,Italy,Europe,Fashion,Luxury,91.0,100.0,NaN,93.0,95.0,...,7.30,27.52,53.71,6.49,11.69,106.71,20.0,20.0,$14.7 b,Private
0,Hermes,France,Europe,Fashion,Luxury,NaN,NaN,73.0,79.0,82.0,...,18.40,67.57,100.00,100.00,87.88,373.85,3.0,3.0,$130.4 b,Public
10,Versace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.68,28.79,39.09,13.95,30.17,133.68,NaN,NaN,NaN,NaN
8,Calvin Klein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.75,22.25,62.08,8.06,50.99,157.13,NaN,NaN,NaN,NaN
25,Salvatore Ferragamo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.62,8.06,54.06,9.64,5.13,78.51,86.0,86.0,$2.48 b,Public
22,Chloe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.45,11.01,58.93,0.00,9.85,82.24,NaN,NaN,NaN,NaN
19,Jovani,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.33,0.87,72.29,10.29,1.77,85.55,NaN,NaN,NaN,NaN
2,Louis Vuitton,France,Europe,Fashion,Luxury,38.0,41.0,45.0,44.0,18.0,...,35.17,50.61,51.18,13.68,100.00,250.64,NaN,NaN,NaN,NaN